// Code generated by "stringer --type=Id"; DO NOT EDIT.

package mimir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[AffiliateFeeBasisPointsMax-1]
	_ = x[BondPause-2]
	_ = x[ConfMultiplierBasisPoints-3]
	_ = x[MaxConfirmations-4]
	_ = x[CloutSwapperLimit-5]
	_ = x[CloutSwapperReset-6]
	_ = x[SwapSlipBasisPointsMin-7]
	_ = x[TradeAccountEnabled-8]
}

const _Id_name = "UnknownAffiliateFeeBasisPointsMaxBondPauseConfMultiplierBasisPointsMaxConfirmationsCloutSwapperLimitCloutSwapperResetSwapSlipBasisPointsMinTradeAccountEnabled"

var _Id_index = [...]uint8{0, 7, 33, 42, 67, 83, 100, 117, 139, 158}

func (i Id) String() string {
	if i < 0 || i >= Id(len(_Id_index)-1) {
		return "Id(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Id_name[_Id_index[i]:_Id_index[i+1]]
}
