// Code generated by "stringer -type=MimirType"; DO NOT EDIT.

package mimir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownMimir-0]
	_ = x[EconomicMimir-1]
	_ = x[OperationalMimir-2]
}

const _MimirType_name = "UnknownMimirEconomicMimirOperationalMimir"

var _MimirType_index = [...]uint8{0, 12, 25, 41}

func (i MimirType) String() string {
	if i >= MimirType(len(_MimirType_index)-1) {
		return "MimirType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MimirType_name[_MimirType_index[i]:_MimirType_index[i+1]]
}
