// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: thorchain/v1/x/thorchain/types/msg_donate.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	common "gitlab.com/thorchain/thornode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgDonate struct {
	Asset       common.Asset                                  `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset"`
	AssetAmount github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,2,opt,name=asset_amount,json=assetAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"asset_amount"`
	RuneAmount  github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,3,opt,name=rune_amount,json=runeAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"rune_amount"`
	Tx          common.Tx                                     `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx"`
	Signer      github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,5,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
}

func (m *MsgDonate) Reset()         { *m = MsgDonate{} }
func (m *MsgDonate) String() string { return proto.CompactTextString(m) }
func (*MsgDonate) ProtoMessage()    {}
func (*MsgDonate) Descriptor() ([]byte, []int) {
	return fileDescriptor_68d86b0fb4c71d85, []int{0}
}
func (m *MsgDonate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDonate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDonate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDonate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDonate.Merge(m, src)
}
func (m *MsgDonate) XXX_Size() int {
	return m.Size()
}
func (m *MsgDonate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDonate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDonate proto.InternalMessageInfo

func (m *MsgDonate) GetAsset() common.Asset {
	if m != nil {
		return m.Asset
	}
	return common.Asset{}
}

func (m *MsgDonate) GetTx() common.Tx {
	if m != nil {
		return m.Tx
	}
	return common.Tx{}
}

func (m *MsgDonate) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgDonate)(nil), "types.MsgDonate")
}

func init() {
	proto.RegisterFile("thorchain/v1/x/thorchain/types/msg_donate.proto", fileDescriptor_68d86b0fb4c71d85)
}

var fileDescriptor_68d86b0fb4c71d85 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe3, 0xfc, 0x6d, 0xa5, 0xba, 0xfd, 0x97, 0x88, 0x21, 0xea, 0xe0, 0x46, 0x2c, 0x94,
	0xa1, 0xb5, 0x0a, 0x4f, 0x90, 0x88, 0xa5, 0x03, 0x12, 0x8a, 0x60, 0x61, 0xa9, 0xd2, 0xc4, 0x72,
	0x22, 0x88, 0x6f, 0x65, 0xbb, 0x28, 0xbc, 0x05, 0x8f, 0x55, 0xb6, 0x8e, 0x88, 0xa1, 0x42, 0xed,
	0x5b, 0x30, 0xa1, 0x38, 0xae, 0x54, 0xc4, 0x82, 0x98, 0xee, 0xf5, 0xd1, 0xb9, 0x9f, 0x75, 0x74,
	0x30, 0xd5, 0x39, 0xc8, 0x34, 0x4f, 0x0a, 0x41, 0x9f, 0xa6, 0xb4, 0x3a, 0x7a, 0xea, 0xe7, 0x25,
	0x53, 0xb4, 0x54, 0x7c, 0x9e, 0x81, 0x48, 0x34, 0x9b, 0x2c, 0x25, 0x68, 0xf0, 0xda, 0x46, 0x1f,
	0x04, 0xdf, 0xee, 0x52, 0x28, 0x4b, 0x10, 0x76, 0x34, 0xc6, 0xc1, 0x09, 0x07, 0x0e, 0x66, 0xa5,
	0xf5, 0xd6, 0xa8, 0xa7, 0xaf, 0x2e, 0xee, 0x5e, 0x2b, 0x7e, 0x65, 0x90, 0xde, 0x39, 0x6e, 0x27,
	0x4a, 0x31, 0xed, 0xa3, 0x00, 0x8d, 0x7a, 0x17, 0xff, 0x27, 0x96, 0x10, 0xd6, 0x62, 0xd4, 0x5a,
	0x6f, 0x87, 0x4e, 0xdc, 0x38, 0xbc, 0x18, 0xf7, 0xcd, 0x32, 0x4f, 0x4a, 0x58, 0x09, 0xed, 0xbb,
	0x01, 0x1a, 0x75, 0x23, 0x5a, 0x5b, 0xde, 0xb7, 0xc3, 0x33, 0x5e, 0xe8, 0x7c, 0xb5, 0xa8, 0xef,
	0x69, 0x0a, 0xaa, 0x04, 0x65, 0xc7, 0x58, 0x65, 0x0f, 0x4d, 0x94, 0xc9, 0x5d, 0x21, 0x74, 0xdc,
	0x33, 0x90, 0xd0, 0x30, 0xbc, 0x1b, 0xdc, 0x93, 0x2b, 0xc1, 0x0e, 0xc8, 0x7f, 0x7f, 0x43, 0xe2,
	0x9a, 0x61, 0x89, 0x01, 0x76, 0x75, 0xe5, 0xb7, 0x4c, 0x1a, 0x7c, 0x48, 0x73, 0x5b, 0xd9, 0x28,
	0xae, 0xae, 0xbc, 0x19, 0xee, 0xa8, 0x82, 0x0b, 0x26, 0xfd, 0x76, 0x80, 0x46, 0xfd, 0x68, 0xfa,
	0xb9, 0x1d, 0x8e, 0x7f, 0xf1, 0x55, 0x98, 0xa6, 0x61, 0x96, 0x49, 0xa6, 0x54, 0x6c, 0x01, 0xd1,
	0x6c, 0xbd, 0x23, 0x68, 0xb3, 0x23, 0xe8, 0x63, 0x47, 0xd0, 0xcb, 0x9e, 0x38, 0x9b, 0x3d, 0x71,
	0xde, 0xf6, 0xc4, 0xb9, 0xa7, 0xbc, 0xd0, 0x8f, 0x49, 0x03, 0x3c, 0x6a, 0x34, 0x07, 0x29, 0x20,
	0x63, 0x3f, 0x6b, 0x5e, 0x74, 0x4c, 0x3b, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0xed,
	0x1a, 0x02, 0x0f, 0x02, 0x00, 0x00,
}

func (m *MsgDonate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDonate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDonate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgDonate(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgDonate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.RuneAmount.Size()
		i -= size
		if _, err := m.RuneAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgDonate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.AssetAmount.Size()
		i -= size
		if _, err := m.AssetAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgDonate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgDonate(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMsgDonate(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgDonate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgDonate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Asset.Size()
	n += 1 + l + sovMsgDonate(uint64(l))
	l = m.AssetAmount.Size()
	n += 1 + l + sovMsgDonate(uint64(l))
	l = m.RuneAmount.Size()
	n += 1 + l + sovMsgDonate(uint64(l))
	l = m.Tx.Size()
	n += 1 + l + sovMsgDonate(uint64(l))
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgDonate(uint64(l))
	}
	return n
}

func sovMsgDonate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgDonate(x uint64) (n int) {
	return sovMsgDonate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgDonate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgDonate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDonate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDonate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgDonate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgDonate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgDonate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgDonate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgDonate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgDonate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AssetAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuneAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgDonate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgDonate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgDonate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RuneAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgDonate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgDonate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgDonate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgDonate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgDonate
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgDonate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgDonate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgDonate
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgDonate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgDonate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgDonate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgDonate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgDonate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgDonate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgDonate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgDonate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgDonate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgDonate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgDonate = fmt.Errorf("proto: unexpected end of group")
)
