// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: thorchain/v1/x/thorchain/types/msg_set_node_keys.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	common "gitlab.com/thorchain/thornode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetNodeKeys struct {
	PubKeySetSet        common.PubKeySet                              `protobuf:"bytes,1,opt,name=pub_key_set_set,json=pubKeySetSet,proto3" json:"pub_key_set_set"`
	ValidatorConsPubKey string                                        `protobuf:"bytes,2,opt,name=validator_cons_pub_key,json=validatorConsPubKey,proto3" json:"validator_cons_pub_key,omitempty"`
	Signer              github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,3,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
}

func (m *MsgSetNodeKeys) Reset()         { *m = MsgSetNodeKeys{} }
func (m *MsgSetNodeKeys) String() string { return proto.CompactTextString(m) }
func (*MsgSetNodeKeys) ProtoMessage()    {}
func (*MsgSetNodeKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36b344690944a7b, []int{0}
}
func (m *MsgSetNodeKeys) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetNodeKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetNodeKeys.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetNodeKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetNodeKeys.Merge(m, src)
}
func (m *MsgSetNodeKeys) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetNodeKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetNodeKeys.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetNodeKeys proto.InternalMessageInfo

func (m *MsgSetNodeKeys) GetPubKeySetSet() common.PubKeySet {
	if m != nil {
		return m.PubKeySetSet
	}
	return common.PubKeySet{}
}

func (m *MsgSetNodeKeys) GetValidatorConsPubKey() string {
	if m != nil {
		return m.ValidatorConsPubKey
	}
	return ""
}

func (m *MsgSetNodeKeys) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgSetNodeKeys)(nil), "types.MsgSetNodeKeys")
}

func init() {
	proto.RegisterFile("thorchain/v1/x/thorchain/types/msg_set_node_keys.proto", fileDescriptor_e36b344690944a7b)
}

var fileDescriptor_e36b344690944a7b = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0xb3, 0xcf, 0xa3, 0x05, 0x63, 0x51, 0x8c, 0x22, 0xa5, 0x87, 0x34, 0x78, 0xea, 0xa5,
	0x5d, 0x6a, 0xc1, 0xa3, 0xd0, 0x7a, 0x2a, 0x45, 0x91, 0xf6, 0xe6, 0x25, 0xe4, 0x65, 0xd8, 0x84,
	0x36, 0x3b, 0x61, 0x67, 0x5b, 0xcc, 0xb7, 0xf0, 0x63, 0xf5, 0xd8, 0xa3, 0xa7, 0x22, 0xcd, 0xb7,
	0xf0, 0x24, 0x79, 0xf1, 0x0d, 0x4f, 0x33, 0x3b, 0xb3, 0xf3, 0xfb, 0xc3, 0xcf, 0xbc, 0xd1, 0x11,
	0xaa, 0x20, 0xf2, 0x62, 0xc9, 0xd7, 0x03, 0xfe, 0xcc, 0xbf, 0x9f, 0x3a, 0x4b, 0x81, 0x78, 0x42,
	0xc2, 0x25, 0xd0, 0xae, 0xc4, 0x10, 0xdc, 0x05, 0x64, 0xd4, 0x4f, 0x15, 0x6a, 0xb4, 0x0e, 0xcb,
	0x75, 0xdb, 0xf9, 0x75, 0x1e, 0x60, 0x92, 0xa0, 0xac, 0x4b, 0xf5, 0xb1, 0x7d, 0x21, 0x50, 0x60,
	0xd9, 0xf2, 0xa2, 0xab, 0xa6, 0x57, 0x5b, 0x66, 0x9e, 0xdc, 0x93, 0x98, 0x83, 0x7e, 0xc0, 0x10,
	0xa6, 0x90, 0x91, 0x75, 0x6b, 0x9e, 0xa6, 0x2b, 0xbf, 0xc8, 0x28, 0x03, 0x09, 0x74, 0x8b, 0x39,
	0xac, 0x7b, 0x7c, 0x7d, 0xd6, 0xaf, 0x81, 0x8f, 0x2b, 0x7f, 0x0a, 0xd9, 0x1c, 0xf4, 0xf8, 0x60,
	0xb3, 0xeb, 0x18, 0xb3, 0x66, 0xfa, 0x39, 0x98, 0x83, 0xb6, 0x86, 0xe6, 0xe5, 0xda, 0x5b, 0xc6,
	0xa1, 0xa7, 0x51, 0xb9, 0x01, 0x4a, 0x72, 0x6b, 0x5c, 0xeb, 0x9f, 0xc3, 0xba, 0x47, 0xb3, 0xf3,
	0xaf, 0xed, 0x1d, 0x4a, 0xaa, 0x58, 0xd6, 0xc4, 0x6c, 0x50, 0x2c, 0x24, 0xa8, 0xd6, 0x7f, 0x87,
	0x75, 0x9b, 0xe3, 0xc1, 0xfb, 0xae, 0xd3, 0x13, 0xb1, 0x8e, 0x56, 0x7e, 0x91, 0xca, 0x03, 0xa4,
	0x04, 0xa9, 0x2e, 0x3d, 0x0a, 0x17, 0x95, 0x96, 0xfe, 0x28, 0x08, 0x46, 0x61, 0xa8, 0x80, 0x68,
	0x56, 0x03, 0xc6, 0x93, 0xcd, 0xde, 0x66, 0xdb, 0xbd, 0xcd, 0xde, 0xf6, 0x36, 0x7b, 0xc9, 0x6d,
	0x63, 0x9b, 0xdb, 0xc6, 0x6b, 0x6e, 0x1b, 0x4f, 0x5c, 0xc4, 0x7a, 0xe9, 0x55, 0xc0, 0x1f, 0x7e,
	0x23, 0x54, 0x85, 0xd5, 0xbf, 0xd2, 0xfd, 0x46, 0x29, 0x69, 0xf8, 0x11, 0x00, 0x00, 0xff, 0xff,
	0x4b, 0xed, 0x35, 0x2b, 0x9d, 0x01, 0x00, 0x00,
}

func (m *MsgSetNodeKeys) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetNodeKeys) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetNodeKeys) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgSetNodeKeys(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ValidatorConsPubKey) > 0 {
		i -= len(m.ValidatorConsPubKey)
		copy(dAtA[i:], m.ValidatorConsPubKey)
		i = encodeVarintMsgSetNodeKeys(dAtA, i, uint64(len(m.ValidatorConsPubKey)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.PubKeySetSet.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgSetNodeKeys(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMsgSetNodeKeys(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgSetNodeKeys(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetNodeKeys) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PubKeySetSet.Size()
	n += 1 + l + sovMsgSetNodeKeys(uint64(l))
	l = len(m.ValidatorConsPubKey)
	if l > 0 {
		n += 1 + l + sovMsgSetNodeKeys(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgSetNodeKeys(uint64(l))
	}
	return n
}

func sovMsgSetNodeKeys(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgSetNodeKeys(x uint64) (n int) {
	return sovMsgSetNodeKeys(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetNodeKeys) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgSetNodeKeys
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetNodeKeys: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetNodeKeys: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeySetSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSetNodeKeys
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgSetNodeKeys
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSetNodeKeys
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PubKeySetSet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorConsPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSetNodeKeys
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgSetNodeKeys
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSetNodeKeys
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorConsPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgSetNodeKeys
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgSetNodeKeys
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgSetNodeKeys
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgSetNodeKeys(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgSetNodeKeys
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgSetNodeKeys
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgSetNodeKeys(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgSetNodeKeys
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgSetNodeKeys
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgSetNodeKeys
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgSetNodeKeys
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgSetNodeKeys
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgSetNodeKeys
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgSetNodeKeys        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgSetNodeKeys          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgSetNodeKeys = fmt.Errorf("proto: unexpected end of group")
)
