// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: thorchain/v1/x/thorchain/types/msg_tss_pool.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	gitlab_com_thorchain_thornode_common "gitlab.com/thorchain/thornode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgTssPool struct {
	ID              string                                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PoolPubKey      gitlab_com_thorchain_thornode_common.PubKey   `protobuf:"bytes,2,opt,name=pool_pub_key,json=poolPubKey,proto3,casttype=gitlab.com/thorchain/thornode/common.PubKey" json:"pool_pub_key,omitempty"`
	KeygenType      KeygenType                                    `protobuf:"varint,3,opt,name=keygen_type,json=keygenType,proto3,enum=types.KeygenType,casttype=KeygenType" json:"keygen_type,omitempty"`
	PubKeys         []string                                      `protobuf:"bytes,4,rep,name=pub_keys,json=pubKeys,proto3" json:"pub_keys,omitempty"`
	Height          int64                                         `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Blame           Blame                                         `protobuf:"bytes,6,opt,name=blame,proto3" json:"blame"`
	Chains          []string                                      `protobuf:"bytes,7,rep,name=chains,proto3" json:"chains,omitempty"`
	Signer          github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,8,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
	KeygenTime      int64                                         `protobuf:"varint,9,opt,name=keygen_time,json=keygenTime,proto3" json:"keygen_time,omitempty"`
	KeysharesBackup []byte                                        `protobuf:"bytes,10,opt,name=keyshares_backup,json=keysharesBackup,proto3" json:"keyshares_backup,omitempty"`
}

func (m *MsgTssPool) Reset()         { *m = MsgTssPool{} }
func (m *MsgTssPool) String() string { return proto.CompactTextString(m) }
func (*MsgTssPool) ProtoMessage()    {}
func (*MsgTssPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_32aba2b7bcac22c3, []int{0}
}
func (m *MsgTssPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTssPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTssPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTssPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTssPool.Merge(m, src)
}
func (m *MsgTssPool) XXX_Size() int {
	return m.Size()
}
func (m *MsgTssPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTssPool.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTssPool proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgTssPool)(nil), "types.MsgTssPool")
}

func init() {
	proto.RegisterFile("thorchain/v1/x/thorchain/types/msg_tss_pool.proto", fileDescriptor_32aba2b7bcac22c3)
}

var fileDescriptor_32aba2b7bcac22c3 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x6e, 0xd4, 0x3c,
	0x14, 0x8d, 0x67, 0x3a, 0x69, 0xc7, 0x1d, 0xf5, 0xfb, 0xb0, 0x50, 0x65, 0xba, 0x48, 0x22, 0x56,
	0x41, 0xa8, 0x31, 0x53, 0x9e, 0xa0, 0x11, 0x9b, 0xaa, 0xaa, 0x54, 0xa2, 0xae, 0xd8, 0x44, 0xf9,
	0xb1, 0x1c, 0x6b, 0x26, 0x71, 0x94, 0x9b, 0x41, 0xcc, 0x5b, 0xf0, 0x56, 0xcc, 0xb2, 0x4b, 0x56,
	0x11, 0xcc, 0xbc, 0xc5, 0xac, 0x90, 0x9d, 0xd0, 0x41, 0x42, 0x02, 0x36, 0xc9, 0x3d, 0xc7, 0x3e,
	0xc7, 0xe7, 0x5e, 0x1b, 0xcf, 0xdb, 0x42, 0x35, 0x59, 0x91, 0xc8, 0x8a, 0x7d, 0x9c, 0xb3, 0x4f,
	0xec, 0x00, 0xdb, 0x75, 0xcd, 0x81, 0x95, 0x20, 0xe2, 0x16, 0x20, 0xae, 0x95, 0x5a, 0x06, 0x75,
	0xa3, 0x5a, 0x45, 0x26, 0x66, 0xe5, 0x82, 0xfd, 0x45, 0xa9, 0xbf, 0x71, 0xba, 0x4c, 0x4a, 0xde,
	0xeb, 0x2e, 0xde, 0xfc, 0x8b, 0x60, 0xc1, 0xd7, 0x82, 0x57, 0x83, 0xe2, 0xb9, 0x50, 0x42, 0x99,
	0x92, 0xe9, 0xaa, 0x67, 0x5f, 0x7e, 0x19, 0x63, 0x7c, 0x07, 0xe2, 0x01, 0xe0, 0x5e, 0xa9, 0x25,
	0x39, 0xc7, 0x23, 0x99, 0x53, 0xe4, 0x21, 0x7f, 0x1a, 0xda, 0xdb, 0xce, 0x1d, 0xdd, 0xbc, 0x8b,
	0x46, 0x32, 0x27, 0xef, 0xf1, 0x4c, 0x87, 0x8e, 0xeb, 0x55, 0xaa, 0x5d, 0xe9, 0xc8, 0xec, 0x60,
	0xfb, 0xce, 0x7d, 0x2d, 0x64, 0xbb, 0x4c, 0xd2, 0x20, 0x53, 0xe5, 0xaf, 0x21, 0x0a, 0xd5, 0x54,
	0x2a, 0xe7, 0x2c, 0x53, 0x65, 0xa9, 0xaa, 0xe0, 0x7e, 0x95, 0xde, 0xf2, 0x75, 0x84, 0xb5, 0x49,
	0x5f, 0x93, 0x10, 0x9f, 0xf6, 0xf9, 0x62, 0x9d, 0x95, 0x8e, 0x3d, 0xe4, 0x9f, 0x5d, 0x3d, 0x0b,
	0x4c, 0xfc, 0xe0, 0xd6, 0xac, 0x3c, 0xac, 0x6b, 0x1e, 0x9e, 0xed, 0x3b, 0x17, 0x1f, 0x70, 0x84,
	0x17, 0x4f, 0x35, 0x79, 0x81, 0x4f, 0x86, 0x44, 0x40, 0x8f, 0xbc, 0xb1, 0x3f, 0x8d, 0x8e, 0x6b,
	0xe3, 0x0e, 0xe4, 0x1c, 0xdb, 0x05, 0x97, 0xa2, 0x68, 0xe9, 0xc4, 0x43, 0xfe, 0x38, 0x1a, 0x10,
	0xf1, 0xf1, 0xc4, 0xcc, 0x91, 0xda, 0x1e, 0xf2, 0x4f, 0xaf, 0x66, 0xc3, 0x81, 0xa1, 0xe6, 0xc2,
	0xa3, 0x4d, 0xe7, 0x5a, 0x51, 0xbf, 0x41, 0x3b, 0x98, 0x66, 0x80, 0x1e, 0x1b, 0xeb, 0x01, 0x91,
	0x1b, 0x6c, 0x83, 0x14, 0x15, 0x6f, 0xe8, 0x89, 0x87, 0xfc, 0x59, 0x38, 0xdf, 0x77, 0xee, 0xa5,
	0x90, 0x6d, 0xb1, 0xea, 0xa7, 0x90, 0x29, 0x28, 0x15, 0x0c, 0xbf, 0x4b, 0xc8, 0x17, 0xfd, 0x95,
	0x04, 0xd7, 0x59, 0x76, 0x9d, 0xe7, 0x0d, 0x07, 0x88, 0x06, 0x03, 0xe2, 0x1e, 0x66, 0x20, 0x4b,
	0x4e, 0xa7, 0x26, 0xe9, 0xcf, 0x06, 0x65, 0xc9, 0xc9, 0x2b, 0xfc, 0xbf, 0x6e, 0xae, 0x48, 0x1a,
	0x0e, 0x71, 0x9a, 0x64, 0x8b, 0x55, 0x4d, 0xb1, 0x3e, 0x35, 0xfa, 0xef, 0x89, 0x0f, 0x0d, 0x1d,
	0xde, 0x6d, 0xbe, 0x3b, 0xd6, 0x66, 0xeb, 0xa0, 0xc7, 0xad, 0x83, 0xbe, 0x6d, 0x1d, 0xf4, 0x79,
	0xe7, 0x58, 0x8f, 0x3b, 0xc7, 0xfa, 0xba, 0x73, 0xac, 0x0f, 0xec, 0xcf, 0xd7, 0xf4, 0xdb, 0x03,
	0x4a, 0x6d, 0xf3, 0x3e, 0xde, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0x08, 0xbd, 0x18, 0xfe, 0xd4,
	0x02, 0x00, 0x00,
}

func (m *MsgTssPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTssPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTssPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.KeysharesBackup) > 0 {
		i -= len(m.KeysharesBackup)
		copy(dAtA[i:], m.KeysharesBackup)
		i = encodeVarintMsgTssPool(dAtA, i, uint64(len(m.KeysharesBackup)))
		i--
		dAtA[i] = 0x52
	}
	if m.KeygenTime != 0 {
		i = encodeVarintMsgTssPool(dAtA, i, uint64(m.KeygenTime))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgTssPool(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Chains) > 0 {
		for iNdEx := len(m.Chains) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Chains[iNdEx])
			copy(dAtA[i:], m.Chains[iNdEx])
			i = encodeVarintMsgTssPool(dAtA, i, uint64(len(m.Chains[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	{
		size, err := m.Blame.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgTssPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.Height != 0 {
		i = encodeVarintMsgTssPool(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PubKeys) > 0 {
		for iNdEx := len(m.PubKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PubKeys[iNdEx])
			copy(dAtA[i:], m.PubKeys[iNdEx])
			i = encodeVarintMsgTssPool(dAtA, i, uint64(len(m.PubKeys[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.KeygenType != 0 {
		i = encodeVarintMsgTssPool(dAtA, i, uint64(m.KeygenType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PoolPubKey) > 0 {
		i -= len(m.PoolPubKey)
		copy(dAtA[i:], m.PoolPubKey)
		i = encodeVarintMsgTssPool(dAtA, i, uint64(len(m.PoolPubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintMsgTssPool(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgTssPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgTssPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgTssPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovMsgTssPool(uint64(l))
	}
	l = len(m.PoolPubKey)
	if l > 0 {
		n += 1 + l + sovMsgTssPool(uint64(l))
	}
	if m.KeygenType != 0 {
		n += 1 + sovMsgTssPool(uint64(m.KeygenType))
	}
	if len(m.PubKeys) > 0 {
		for _, s := range m.PubKeys {
			l = len(s)
			n += 1 + l + sovMsgTssPool(uint64(l))
		}
	}
	if m.Height != 0 {
		n += 1 + sovMsgTssPool(uint64(m.Height))
	}
	l = m.Blame.Size()
	n += 1 + l + sovMsgTssPool(uint64(l))
	if len(m.Chains) > 0 {
		for _, s := range m.Chains {
			l = len(s)
			n += 1 + l + sovMsgTssPool(uint64(l))
		}
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgTssPool(uint64(l))
	}
	if m.KeygenTime != 0 {
		n += 1 + sovMsgTssPool(uint64(m.KeygenTime))
	}
	l = len(m.KeysharesBackup)
	if l > 0 {
		n += 1 + l + sovMsgTssPool(uint64(l))
	}
	return n
}

func sovMsgTssPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgTssPool(x uint64) (n int) {
	return sovMsgTssPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgTssPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgTssPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTssPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTssPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolPubKey = gitlab_com_thorchain_thornode_common.PubKey(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeygenType", wireType)
			}
			m.KeygenType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeygenType |= KeygenType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKeys = append(m.PubKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blame", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Blame.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chains", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chains = append(m.Chains, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeygenTime", wireType)
			}
			m.KeygenTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeygenTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeysharesBackup", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeysharesBackup = append(m.KeysharesBackup[:0], dAtA[iNdEx:postIndex]...)
			if m.KeysharesBackup == nil {
				m.KeysharesBackup = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgTssPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgTssPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgTssPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgTssPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgTssPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgTssPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgTssPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgTssPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgTssPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgTssPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgTssPool = fmt.Errorf("proto: unexpected end of group")
)
